```{r}
library(tidyverse)
library(lubridate)
library(rvest)
library(janitor)
```

```{r}
urls <- read_csv("url_csvs/NCAA Volleyball - 2020.csv") %>% pull(1)
```

```{r}
root_url <- "https://stats.ncaa.org"
season = "2020"

urltibble <- tibble(
  school = character(),
  playerstatsurl = character(),
  matchstatsurl = character()
)

urlfilename <- paste0("url_csvs/ncaa_womens_volleyball_teamurls_", season, ".csv")
```

```{r}
for (i in urls){

schoolpage <- i %>% read_html()

schoolfull <- schoolpage %>% html_nodes(xpath = '//*[@id="contentarea"]/fieldset[1]/legend/a[1]') %>% html_text()

playerstats_url <- schoolpage %>% html_nodes(xpath = '//*[@id="contentarea"]/a[2]') %>% html_attr('href')

matchstats_url <- schoolpage %>% html_nodes(xpath = '//*[@id="contentarea"]/a[3]') %>% html_attr('href')

playerstats <- paste(root_url, playerstats_url, sep="") %>% read_html() %>% html_nodes(xpath = '//*[@id="stat_grid"]') %>% html_table()

urltibble <- urltibble %>% add_row(school = schoolfull, playerstatsurl = paste0(root_url, playerstats_url), matchstatsurl = paste0(root_url, matchstats_url))

message <- paste0("Grabbing urls for ", schoolfull)

print(message)

Sys.sleep(2)
}
```

```{r}
write_csv(urltibble, urlfilename)
```


